#spring:
#  kafka:
#    bootstrap-servers: 10.10.11.36:9092
#    producer:
#      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#    consumer:
#      group-id: test
#      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      auto-offset-reset: latest
#      enable-auto-commit: true
#      bootstrap-servers: 10.10.11.36:9092
#    properties:
#      schema.registry.url: 10.10.11.36:8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # Configures the Spring Kafka ErrorHandlingDeserializer that delegates to the 'real' deserializers
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      # Delegate deserializers
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer